uwsgi:
  build: uwsgi
nginx:
  build: nginx
  links:
    - uwsgi
  expose:
    - 8000
  ports:
    - "8000:8000"
chromedriver:
  build: docker-chromedriver
  links:
    - nginx
  ports:
    - "4444:4444"
  environment:
    CHROMEDRIVER_WHITELISTED_IPS: ""