uwsgi:
  build: uwsgi
nginx:
  build: nginx
  links:
    - uwsgi
  expose:
    - 8000
  ports:
    - "8000:8000"
chromedriver:
  image: robcherry/docker-chromedriver:latest
  links:
    - nginx
  ports:
    - "4444:4444"
  environment:
    CHROMEDRIVER_WHITELISTED_IPS: ""